
CREATE TABLE TRANSACTIONS (
    TXN_ID VARCHAR2(50) PRIMARY KEY,
    AMOUNT NUMBER,
    STATUS VARCHAR2(20)
);


INSERT INTO TRANSACTIONS VALUES ('TXN001', 1000, 'SUCCESS');
INSERT INTO TRANSACTIONS VALUES ('TXN002', 1500, 'FAILED');
INSERT INTO TRANSACTIONS VALUES ('TXN003', 2000, 'SUCCESS');
INSERT INTO TRANSACTIONS VALUES ('TXN004', 2500, 'PENDING');
INSERT INTO TRANSACTIONS VALUES ('TXN005', 3000, 'SUCCESS');
INSERT INTO TRANSACTIONS VALUES ('TXN006', 1200, 'FAILED');
INSERT INTO TRANSACTIONS VALUES ('TXN007', 1800, 'SUCCESS');
INSERT INTO TRANSACTIONS VALUES ('TXN008', 2200, 'PENDING');
INSERT INTO TRANSACTIONS VALUES ('TXN009', 2700, 'SUCCESS');
INSERT INTO TRANSACTIONS VALUES ('TXN010', 3500, 'FAILED');



CREATE TABLE RECONCILIATION (
    TXN_ID VARCHAR2(50),
    RECON_STATUS VARCHAR2(20)
);


INSERT INTO RECONCILIATION VALUES ('TXN001', 'MATCHED');
INSERT INTO RECONCILIATION VALUES ('TXN002', 'MISMATCH');
INSERT INTO RECONCILIATION VALUES ('TXN003', 'MATCHED');
INSERT INTO RECONCILIATION VALUES ('TXN004', 'PENDING');
INSERT INTO RECONCILIATION VALUES ('TXN005', 'MATCHED');
INSERT INTO RECONCILIATION VALUES ('TXN006', 'MISMATCH');
INSERT INTO RECONCILIATION VALUES ('TXN007', 'MATCHED');
INSERT INTO RECONCILIATION VALUES ('TXN008', 'PENDING');
INSERT INTO RECONCILIATION VALUES ('TXN009', 'MATCHED');
INSERT INTO RECONCILIATION VALUES ('TXN011', 'MISSING'); -- Not in TRANSACTIONS (test case)


SELECT * FROM USER_TABLES WHERE TABLE_NAME = 'TRANSACTIONS';


-- few changes in old table
DELETE FROM TRANSACTIONS;

INSERT INTO TRANSACTIONS (TXN_ID, AMOUNT, STATUS)
VALUES ('TXN12345', 500, 'SUCCESS');

COMMIT;

SELECT * FROM TRANSACTIONS;